FROM nginx:stable-alpine

LABEL maintainer="Wowcher Ops <ops@wowcher.co.uk>"

COPY .next/ /usr/share/nginx/html/
COPY ./run_nginx.sh ./run_nginx.sh

RUN rm /etc/nginx/conf.d/default.conf; \
    rm /usr/share/nginx/html/index.html; \
    chmod a+x run_nginx.sh; \
    ln -s /usr/share/nginx/html/server/static/*/pages/index.html /usr/share/nginx/html/index.html;

COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
ENTRYPOINT ["/run_nginx.sh"]
